name: Build & Test

on:
  pull_request:
    branches: [ "main" ]   # se ejecuta en PRs hacia master

permissions:
  contents: read

jobs:
  build:
    name: build
    uses: IngSisG10/snippet-infrastructure/.github/workflows/new_version_workflow.yml@main
    secrets: inherit
